[package]
name = "manifest-feature-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fallible-iterator = "0.2.0"
heck = "0.4.0"
thiserror = "1.0.37"
toml_edit = { version = "0.15.0" }
