name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - name: run rustfmt
      run: cargo fmt --check
    - name: Test
      run: cargo test --all --verbose
    - name: Clippy
      run: cargo clippy --all --verbose
